/* Generated by the Nim Compiler v2.0.5 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33554466 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI671088654 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI872415311 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI872415317 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI33555838 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555173 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555181 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555180 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555177 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555178 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
var NNI33555178 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555178.node = NNI33555178;
NTI33555180.base = NTI33555177;
NTI33555181.base = NTI33555177;
var NNI33555177 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555180, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555181, name: "up", sons: null}]};
NTI33555177.node = NNI33555177;
var NNI33555173 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555173.node = NNI33555173;
NTI33555177.base = NTI33555173;
NTI33555178.base = NTI33555177;
NTI134217741.base = NTI33555178;
NTI134217743.base = NTI134217741;
var NNI33555838 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554450, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI33554450, name: "Field2", sons: null}]};
NTI33555838.node = NNI33555838;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555178;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555178;
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
NTI134217745.base = NTI33555178;
var NNI872415317 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a", len: 0, typ: NTI872415311, name: "a", sons: null}, 
{kind: 1, offset: "b", len: 0, typ: NTI33554435, name: "b", sons: null}]};
NTI872415317.node = NNI872415317;
var NNI671088654 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554435, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554466, name: "Field1", sons: null}]};
NTI671088654.node = NNI671088654;

function mnewString(len_33557003) {
        var result = new Array(len_33557003);
    for (var i = 0; i < len_33557003; i++) {result[i] = 0;}
    return result;
  

  
}

function arrayConstr(len_33557314, value_33557315, typ_33557316) {
        var result = new Array(len_33557314);
    for (var i = 0; i < len_33557314; ++i) result[i] = nimCopy(null, value_33557315, typ_33557316);
    return result;
  

  
}

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_33557268, src_33557269, ti_33557270) {
  var result_33557279 = null;

    switch (ti_33557270.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_33557259(ti_33557270))) {
      result_33557279 = src_33557269;
      }
      else {
        result_33557279 = [src_33557269[0], src_33557269[1]];
      }
      
      break;
    case 19:
            if (dest_33557268 === null || dest_33557268 === undefined) {
        dest_33557268 = {};
      }
      else {
        for (var key in dest_33557268) { delete dest_33557268[key]; }
      }
      for (var key in src_33557269) { dest_33557268[key] = src_33557269[key]; }
      result_33557279 = dest_33557268;
    
      break;
    case 18:
    case 17:
      if (!((ti_33557270.base == null))) {
      result_33557279 = nimCopy(dest_33557268, src_33557269, ti_33557270.base);
      }
      else {
      if ((ti_33557270.kind == 17)) {
      result_33557279 = (dest_33557268 === null || dest_33557268 === undefined) ? {m_type: ti_33557270} : dest_33557268;
      }
      else {
        result_33557279 = (dest_33557268 === null || dest_33557268 === undefined) ? {} : dest_33557268;
      }
      }
      nimCopyAux(result_33557279, src_33557269, ti_33557270.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_33557269)) { 
        if(dest_33557268 === null || dest_33557268 === undefined || dest_33557268.length != src_33557269.length) {
          dest_33557268 = new src_33557269.constructor(src_33557269);
        } else {
          dest_33557268.set(src_33557269, 0);
        }
        result_33557279 = dest_33557268;
      } else {
        if (src_33557269 === null) {
          result_33557279 = null;
        }
        else {
          if (dest_33557268 === null || dest_33557268 === undefined || dest_33557268.length != src_33557269.length) {
            dest_33557268 = new Array(src_33557269.length);
          }
          result_33557279 = dest_33557268;
          for (var i = 0; i < src_33557269.length; ++i) {
            result_33557279[i] = nimCopy(result_33557279[i], src_33557269[i], ti_33557270.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_33557269 === null) {
        result_33557279 = null;
      }
      else {
        if (dest_33557268 === null || dest_33557268 === undefined || dest_33557268.length != src_33557269.length) {
          dest_33557268 = new Array(src_33557269.length);
        }
        result_33557279 = dest_33557268;
        for (var i = 0; i < src_33557269.length; ++i) {
          result_33557279[i] = nimCopy(result_33557279[i], src_33557269[i], ti_33557270.base);
        }
      }
    
      break;
    case 28:
            if (src_33557269 !== null) {
        result_33557279 = src_33557269.slice(0);
      }
    
      break;
    default: 
      result_33557279 = src_33557269;
      break;
    }

  return result_33557279;

}

function cstrToNimstr(c_33556898) {
      var ln = c_33556898.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_33556898.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_33556898.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}

function toJSStr(s_33556901) {
  var result_33556902 = null;

    var res_33556943 = newSeq_33556919((s_33556901).length);
    var i_33556944 = 0;
    var j_33556945 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556944 < (s_33556901).length)) break Label2;
          var c_33556946 = s_33556901[i_33556944];
          if ((c_33556946 < 128)) {
          res_33556943[j_33556945] = String.fromCharCode(c_33556946);
          i_33556944 += 1;
          }
          else {
            var helper_33556959 = newSeq_33556919(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556960 = c_33556946.toString(16);
                  if ((((code_33556960) == null ? 0 : (code_33556960).length) == 1)) {
                  helper_33556959.push("%0");;
                  }
                  else {
                  helper_33556959.push("%");;
                  }
                  
                  helper_33556959.push(code_33556960);;
                  i_33556944 += 1;
                  if ((((s_33556901).length <= i_33556944) || (s_33556901[i_33556944] < 128))) {
                  break Label3;
                  }
                  
                  c_33556946 = s_33556901[i_33556944];
                }
            };
++excHandler;
            try {
            res_33556943[j_33556945] = decodeURIComponent(helper_33556959.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556943[j_33556945] = helper_33556959.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556945 += 1;
        }
    };
    if (res_33556943.length < j_33556945) { for (var i = res_33556943.length ; i < j_33556945 ; ++i) res_33556943.push(null); }
               else { res_33556943.length = j_33556945; };
    result_33556902 = res_33556943.join("");

  return result_33556902;

}

function raiseException(e_33556653, ename_33556654) {
    e_33556653.name = ename_33556654;
    if ((excHandler == 0)) {
    unhandledException(e_33556653);
    }
    
    e_33556653.trace = nimCopy(null, rawWriteStackTrace_33556604(), NTI33554449);
    throw e_33556653;

  
}

function addInt(a_33557050, b_33557051) {
        var result = a_33557050 + b_33557051;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_33557324, a_33557325, b_33557326) {
  var result_33557327 = 0;

  BeforeRet: {
    if (((a_33557325 <= i_33557324) && (i_33557324 <= b_33557326))) {
    result_33557327 = i_33557324;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557327;

}

function chckIndx(i_33557319, a_33557320, b_33557321) {
  var result_33557322 = 0;

  BeforeRet: {
    if (((a_33557320 <= i_33557319) && (i_33557319 <= b_33557321))) {
    result_33557322 = i_33557319;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_33557319, a_33557320, b_33557321);
    }
    
  };

  return result_33557322;

}

function makeNimstrLit(c_33556895) {
      var result = [];
  for (var i = 0; i < c_33556895.length; ++i) {
    result[i] = c_33556895.charCodeAt(i);
  }
  return result;
  

  
}

function subInt(a_33557054, b_33557055) {
        var result = a_33557054 - b_33557055;
    checkOverflowInt(result);
    return result;
  

  
}
var ConstSet2 = setConstr([65, 90]);
var ConstSet3 = setConstr(95, 32, 46);
var ConstSet4 = setConstr(95, 32, 46);

function mulInt(a_33557058, b_33557059) {
        var result = a_33557058 * b_33557059;
    checkOverflowInt(result);
    return result;
  

  
}
var ConstSet5 = setConstr([97, 122]);
var ConstSet6 = setConstr([65, 90], [97, 122]);
var ConstSet7 = setConstr([97, 122]);
var ConstSet8 = setConstr([65, 90]);
var ConstSet9 = setConstr([65, 90], [97, 122]);

function nimMax(a_33557108, b_33557109) {
    var Temporary1;

  var result_33557110 = 0;

  BeforeRet: {
    if ((b_33557109 <= a_33557108)) {
    Temporary1 = a_33557108;
    }
    else {
    Temporary1 = b_33557109;
    }
    
    result_33557110 = Temporary1;
    break BeforeRet;
  };

  return result_33557110;

}

function nimMin(a_33557104, b_33557105) {
    var Temporary1;

  var result_33557106 = 0;

  BeforeRet: {
    if ((a_33557104 <= b_33557105)) {
    Temporary1 = a_33557104;
    }
    else {
    Temporary1 = b_33557105;
    }
    
    result_33557106 = Temporary1;
    break BeforeRet;
  };

  return result_33557106;

}

function addChar(x_33557415, c_33557416) {
    x_33557415.push(c_33557416);

  
}
var F = {procname: "module dom", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/js/dom.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module dom", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/js/dom.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fuzzysearch", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/fuzzysearch.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fuzzysearch", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/fuzzysearch.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module hashes", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/pure/hashes.nim", line: 0};
framePtr = F;
F.line = 218;
F.filename = "hashes.nim";
var objectID_1040187569 = [0];
framePtr = F.prev;
var F = {procname: "module hashes", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/pure/hashes.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module outparams", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/std/outparams.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module outparams", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/std/outparams.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/pure/collections/tables.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/pure/collections/tables.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsffi", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/js/jsffi.nim", line: 0};
framePtr = F;
F.line = 45;
F.filename = "jsffi.nim";
F.line = 46;
framePtr = F.prev;
var F = {procname: "module jsffi", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/js/jsffi.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/js/asyncjs.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/js/asyncjs.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsformdata", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/std/jsformdata.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsheaders", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/std/jsheaders.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsheaders", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/std/jsheaders.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module httpcore", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/pure/httpcore.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module httpcore", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/pure/httpcore.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsfetch", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/std/jsfetch.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsfetch", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/std/jsfetch.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function setTheme(theme_520093702) {
  var F = {procname: "dochack.setTheme", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
  framePtr = F;
    F.line = 7;
    F.filename = "dochack.nim";
    document.documentElement.setAttribute("data-theme", theme_520093702);
    F.line = 8;
    window.localStorage.setItem("theme", theme_520093702);
  framePtr = F.prev;

  
}

function add_33556373(x_33556374, x_33556374_Idx, y_33556375) {
          if (x_33556374[x_33556374_Idx] === null) { x_33556374[x_33556374_Idx] = []; }
      var off = x_33556374[x_33556374_Idx].length;
      x_33556374[x_33556374_Idx].length += y_33556375.length;
      for (var i = 0; i < y_33556375.length; ++i) {
        x_33556374[x_33556374_Idx][off+i] = y_33556375.charCodeAt(i);
      }
    

  
}

function isFatPointer_33557259(ti_33557260) {
  var result_33557261 = false;

  BeforeRet: {
    result_33557261 = !((ConstSet1[ti_33557260.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557261;

}

function nimCopyAux(dest_33557272, src_33557273, n_33557274) {
    switch (n_33557274.kind) {
    case 0:
      break;
    case 1:
            dest_33557272[n_33557274.offset] = nimCopy(dest_33557272[n_33557274.offset], src_33557273[n_33557274.offset], n_33557274.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_33557274.sons.length; i++) {
      nimCopyAux(dest_33557272, src_33557273, n_33557274.sons[i]);
    }
    
      break;
    case 3:
            dest_33557272[n_33557274.offset] = nimCopy(dest_33557272[n_33557274.offset], src_33557273[n_33557274.offset], n_33557274.typ);
      for (var i = 0; i < n_33557274.sons.length; ++i) {
        nimCopyAux(dest_33557272, src_33557273, n_33557274.sons[i][1]);
      }
    
      break;
    }

  
}

function auxWriteStackTrace_33556508(f_33556509) {
  var result_33556510 = [[]];

    var it_33556518 = f_33556509;
    var i_33556519 = 0;
    var total_33556520 = 0;
    var tempFrames_33556521 = arrayConstr(64, {Field0: null, Field1: 0, Field2: null}, NTI33555838);
    Label1: {
        Label2: while (true) {
        if (!(!((it_33556518 == null)) && (i_33556519 <= 63))) break Label2;
          tempFrames_33556521[i_33556519].Field0 = it_33556518.procname;
          tempFrames_33556521[i_33556519].Field1 = it_33556518.line;
          tempFrames_33556521[i_33556519].Field2 = it_33556518.filename;
          i_33556519 += 1;
          total_33556520 += 1;
          it_33556518 = it_33556518.prev;
        }
    };
    Label3: {
        Label4: while (true) {
        if (!!((it_33556518 == null))) break Label4;
          total_33556520 += 1;
          it_33556518 = it_33556518.prev;
        }
    };
    result_33556510[0] = nimCopy(null, [], NTI33554449);
    if (!((total_33556520 == i_33556519))) {
    result_33556510[0].push.apply(result_33556510[0], [40]);;
    result_33556510[0].push.apply(result_33556510[0], HEX24_369098760((total_33556520 - i_33556519)));;
    result_33556510[0].push.apply(result_33556510[0], [32,99,97,108,108,115,32,111,109,105,116,116,101,100,41,32,46,46,46,10]);;
    }
    
    Label5: {
      var j_33556554 = 0;
      var colontmp__520094902 = 0;
      colontmp__520094902 = (i_33556519 - 1);
      var res_520094904 = colontmp__520094902;
      Label6: {
          Label7: while (true) {
          if (!(0 <= res_520094904)) break Label7;
            j_33556554 = res_520094904;
            result_33556510[0].push.apply(result_33556510[0], cstrToNimstr(tempFrames_33556521[j_33556554].Field2));;
            if ((0 < tempFrames_33556521[j_33556554].Field1)) {
            result_33556510[0].push.apply(result_33556510[0], [40]);;
            addInt_301990129(result_33556510, 0, tempFrames_33556521[j_33556554].Field1);
            if (false) {
            result_33556510[0].push.apply(result_33556510[0], [44,32]);;
            addInt_301990129(result_33556510, 0, 0);
            }
            
            result_33556510[0].push.apply(result_33556510[0], [41]);;
            }
            
            result_33556510[0].push.apply(result_33556510[0], [32,97,116,32]);;
            add_33556373(result_33556510, 0, tempFrames_33556521[j_33556554].Field0);
            result_33556510[0].push.apply(result_33556510[0], [10]);;
            res_520094904 -= 1;
          }
      };
    };

  return result_33556510[0];

}

function rawWriteStackTrace_33556604() {
  var result_33556605 = [];

    if (!((framePtr == null))) {
    result_33556605 = nimCopy(null, ([84,114,97,99,101,98,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,108,97,115,116,41,10] || []).concat(auxWriteStackTrace_33556508(framePtr) || []), NTI33554449);
    }
    else {
      result_33556605 = nimCopy(null, [78,111,32,115,116,97,99,107,32,116,114,97,99,101,98,97,99,107,32,97,118,97,105,108,97,98,108,101,10], NTI33554449);
    }
    

  return result_33556605;

}

function newSeq_33556919(len_33556921) {
  var result_33556922 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 631;
    F.filename = "system.nim";
    result_33556922 = new Array(len_33556921); for (var i = 0 ; i < len_33556921 ; ++i) { result_33556922[i] = null; }  framePtr = F.prev;

  return result_33556922;

}

function unhandledException(e_33556649) {
    var buf_33556650 = [[]];
    if (!(((e_33556649.message).length == 0))) {
    buf_33556650[0].push.apply(buf_33556650[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556650[0].push.apply(buf_33556650[0], e_33556649.message);;
    }
    else {
    buf_33556650[0].push.apply(buf_33556650[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    buf_33556650[0].push.apply(buf_33556650[0], [32,91]);;
    add_33556373(buf_33556650, 0, e_33556649.name);
    buf_33556650[0].push.apply(buf_33556650[0], [93,10]);;
    buf_33556650[0].push.apply(buf_33556650[0], rawWriteStackTrace_33556604());;
    var cbuf_33556651 = toJSStr(buf_33556650[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556651);
  }
  else {
    throw cbuf_33556651;
  }
  

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_33557048) {
        if (a_33557048 > 2147483647 || a_33557048 < -2147483648) raiseOverflow();
  

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function addChars_301990090(result_301990092, result_301990092_Idx, x_301990093, start_301990094, n_301990095) {
    var Temporary1;

  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 43;
    F.filename = "digitsutils.nim";
    var old_301990096 = (result_301990092[result_301990092_Idx]).length;
    F.line = 44;
    if (result_301990092[result_301990092_Idx].length < (Temporary1 = chckRange(addInt(old_301990096, n_301990095), 0, 2147483647), Temporary1)) { for (var i = result_301990092[result_301990092_Idx].length; i < Temporary1; ++i) result_301990092[result_301990092_Idx].push(0); }
         else {result_301990092[result_301990092_Idx].length = Temporary1; };
    Label2: {
      F.line = 46;
      var iHEX60gensym4_301990110 = 0;
      F.line = 128;
      F.filename = "iterators_1.nim";
      var i_520094897 = 0;
      Label3: {
        F.line = 129;
          Label4: while (true) {
          if (!(i_520094897 < n_301990095)) break Label4;
            F.line = 49;
            F.filename = "digitsutils.nim";
            iHEX60gensym4_301990110 = i_520094897;
            F.line = 49;
            result_301990092[result_301990092_Idx][chckIndx(addInt(old_301990096, iHEX60gensym4_301990110), 0, (result_301990092[result_301990092_Idx]).length - 1)] = x_301990093.charCodeAt(chckIndx(addInt(start_301990094, iHEX60gensym4_301990110), 0, (x_301990093).length - 1));
            F.line = 131;
            F.filename = "iterators_1.nim";
            i_520094897 = addInt(i_520094897, 1);
          }
      };
    };
  framePtr = F.prev;

  
}

function addChars_301990086(result_301990088, result_301990088_Idx, x_301990089) {
  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 55;
    F.filename = "digitsutils.nim";
    addChars_301990090(result_301990088, result_301990088_Idx, x_301990089, 0, ((x_301990089) == null ? 0 : (x_301990089).length));
  framePtr = F.prev;

  
}

function addInt_301990111(result_301990112, result_301990112_Idx, x_301990113) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 111;
    F.filename = "digitsutils.nim";
    addChars_301990086(result_301990112, result_301990112_Idx, ((x_301990113) + ""));
  framePtr = F.prev;

  
}

function addInt_301990129(result_301990130, result_301990130_Idx, x_301990131) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 115;
    F.filename = "digitsutils.nim";
    addInt_301990111(result_301990130, result_301990130_Idx, BigInt(x_301990131));
  framePtr = F.prev;

  
}

function HEX24_369098760(x_369098761) {
  var result_369098762 = [[]];

  var F = {procname: "dollars.$", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/system/dollars.nim", line: 0};
  framePtr = F;
    F.line = 18;
    F.filename = "dollars.nim";
    addInt_301990129(result_369098762, 0, x_369098761);
  framePtr = F.prev;

  return result_369098762[0];

}

function raiseIndexError(i_33556812, a_33556813, b_33556814) {
    var Temporary1;

    if ((b_33556814 < a_33556813)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32] || []).concat(HEX24_369098760(i_33556812) || [],[32,110,111,116,32,105,110,32] || [],HEX24_369098760(a_33556813) || [],[32,46,46,32] || [],HEX24_369098760(b_33556814) || []);
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function sysFatal_268435501(message_268435504) {
  var F = {procname: "sysFatal.sysFatal", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/system/fatal.nim", line: 0};
  framePtr = F;
    F.line = 53;
    F.filename = "fatal.nim";
    raiseException({message: nimCopy(null, message_268435504, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");
  framePtr = F.prev;

  
}

function raiseAssert_268435499(msg_268435500) {
  var F = {procname: "assertions.raiseAssert", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 36;
    F.filename = "assertions.nim";
    sysFatal_268435501(msg_268435500);
  framePtr = F.prev;

  
}

function failedAssertImpl_268435541(msg_268435542) {
  var F = {procname: "assertions.failedAssertImpl", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 41;
    F.filename = "assertions.nim";
    raiseAssert_268435499(msg_268435542);
  framePtr = F.prev;

  
}

function onDOMLoaded(e_520093737) {
            
function HEX3Aanonymous_520093761(event_520093762) {
              var F = {procname: "onDOMLoaded.:anonymous", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
              framePtr = F;
                F.line = 22;
                F.filename = "dochack.nim";
                event_520093762.target.parentNode.style.display = "none";
                F.line = 24;
                event_520093762.target.parentNode.nextSibling.style.display = "inline";
              framePtr = F.prev;

              
            }

  var F = {procname: "dochack.onDOMLoaded", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
  framePtr = F;
    F.line = 17;
    F.filename = "dochack.nim";
    document.getElementById("theme-select").value = window.localStorage.getItem("theme");
    Label1: {
      F.line = 19;
      var pragmaDots_520093760 = null;
      F.line = 247;
      F.filename = "iterators.nim";
      var colontmp__520094888 = [];
      F.line = 19;
      F.filename = "dochack.nim";
      colontmp__520094888 = document.getElementsByClassName("pragmadots");
      F.line = 249;
      F.filename = "iterators.nim";
      var i_520094890 = 0;
      F.line = 250;
      var L_520094891 = (colontmp__520094888).length;
      Label2: {
        F.line = 251;
          Label3: while (true) {
          if (!(i_520094890 < L_520094891)) break Label3;
            F.line = 19;
            F.filename = "dochack.nim";
            pragmaDots_520093760 = colontmp__520094888[chckIndx(i_520094890, 0, (colontmp__520094888).length - 1)];
            F.line = 19;
            pragmaDots_520093760.onclick = HEX3Aanonymous_520093761;
            F.line = 13;
            F.filename = "iterators.nim";
            i_520094890 += 1;
            if (!(((colontmp__520094888).length == L_520094891))) {
            F.line = 254;
            failedAssertImpl_268435541(makeNimstrLit("/home/runner/work/Arraymancer/Arraymancer/nim/lib/system/iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
  framePtr = F.prev;

  
}

function isWhitespace_520094104(x_520094105) {
  var result_520094106 = false;

  var F = {procname: "dochack.isWhitespace", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
  framePtr = F;
    F.line = 119;
    F.filename = "dochack.nim";
    result_520094106 = (((x_520094105.nodeName == "#text") && !/\S/.test(x_520094105.textContent)) || (x_520094105.nodeName == "#comment"));
  framePtr = F.prev;

  return result_520094106;

}

function toToc_520094107(x_520094108, father_520094109) {
                var Temporary5;
            var Temporary6;
            var Temporary7;
            var Temporary8;
      var Temporary15;

  var F = {procname: "dochack.toToc", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
  framePtr = F;
    if ((x_520094108.nodeName == "UL")) {
    F.line = 123;
    F.filename = "dochack.nim";
    var f_520094117 = {heading: null, kids: [], sortId: (father_520094109.kids).length, doSort: false};
    F.line = 124;
    var i_520094118 = 0;
    Label1: {
      F.line = 125;
        Label2: while (true) {
        if (!(i_520094118 < x_520094108.childNodes.length)) break Label2;
          F.line = 126;
          var nxt_520094119 = addInt(i_520094118, 1);
          Label3: {
            F.line = 127;
              Label4: while (true) {
                if (!(nxt_520094119 < x_520094108.childNodes.length)) Temporary5 = false; else {                  Temporary5 = isWhitespace_520094104(x_520094108.childNodes[nxt_520094119]);                }              if (!Temporary5) break Label4;
                F.line = 128;
                nxt_520094119 = addInt(nxt_520094119, 1);
              }
          };
            if (!(nxt_520094119 < x_520094108.childNodes.length)) Temporary8 = false; else {              Temporary8 = (x_520094108.childNodes[i_520094118].nodeName == "LI");            }            if (!Temporary8) Temporary7 = false; else {              Temporary7 = (x_520094108.childNodes[i_520094118].childNodes.length == 1);            }            if (!Temporary7) Temporary6 = false; else {              Temporary6 = (x_520094108.childNodes[nxt_520094119].nodeName == "UL");            }          if (Temporary6) {
          F.line = 131;
          var e_520094132 = {heading: x_520094108.childNodes[i_520094118].childNodes[0], kids: [], sortId: (f_520094117.kids).length, doSort: false};
          F.line = 132;
          var it_520094133 = x_520094108.childNodes[nxt_520094119];
          Label9: {
            F.line = 133;
            var j_520094138 = 0;
            F.line = 126;
            F.filename = "iterators_1.nim";
            var colontmp__520094911 = 0;
            F.line = 133;
            F.filename = "dochack.nim";
            colontmp__520094911 = it_520094133.childNodes.length;
            F.line = 128;
            F.filename = "iterators_1.nim";
            var i_520094912 = 0;
            Label10: {
              F.line = 129;
                Label11: while (true) {
                if (!(i_520094912 < colontmp__520094911)) break Label11;
                  F.line = 133;
                  F.filename = "dochack.nim";
                  j_520094138 = i_520094912;
                  F.line = 133;
                  toToc_520094107(it_520094133.childNodes[j_520094138], e_520094132);
                  F.line = 131;
                  F.filename = "iterators_1.nim";
                  i_520094912 = addInt(i_520094912, 1);
                }
            };
          };
          F.line = 135;
          F.filename = "dochack.nim";
          f_520094117.kids.push(e_520094132);;
          F.line = 136;
          i_520094118 = addInt(nxt_520094119, 1);
          }
          else {
            F.line = 138;
            toToc_520094107(x_520094108.childNodes[i_520094118], f_520094117);
            F.line = 139;
            i_520094118 = addInt(i_520094118, 1);
          }
          
        }
    };
    F.line = 140;
    father_520094109.kids.push(f_520094117);;
    }
    else {
    if (isWhitespace_520094104(x_520094108)) {
    }
    else {
    if ((x_520094108.nodeName == "LI")) {
    F.line = 144;
    var idx_520094156 = [];
    Label12: {
      F.line = 145;
      var i_520094161 = 0;
      F.line = 126;
      F.filename = "iterators_1.nim";
      var colontmp__520094915 = 0;
      F.line = 145;
      F.filename = "dochack.nim";
      colontmp__520094915 = x_520094108.childNodes.length;
      F.line = 128;
      F.filename = "iterators_1.nim";
      var i_520094916 = 0;
      Label13: {
        F.line = 129;
          Label14: while (true) {
          if (!(i_520094916 < colontmp__520094915)) break Label14;
            F.line = 145;
            F.filename = "dochack.nim";
            i_520094161 = i_520094916;
            if (!(isWhitespace_520094104(x_520094108.childNodes[i_520094161]))) {
            F.line = 146;
            idx_520094156.push(i_520094161);;
            }
            
            F.line = 131;
            F.filename = "iterators_1.nim";
            i_520094916 = addInt(i_520094916, 1);
          }
      };
    };
      if (!((idx_520094156).length == 2)) Temporary15 = false; else {        Temporary15 = (x_520094108.childNodes[idx_520094156[chckIndx(1, 0, (idx_520094156).length - 1)]].nodeName == "UL");      }    if (Temporary15) {
    F.line = 148;
    F.filename = "dochack.nim";
    var e_520094177 = {heading: x_520094108.childNodes[idx_520094156[chckIndx(0, 0, (idx_520094156).length - 1)]], kids: [], sortId: (father_520094109.kids).length, doSort: false};
    F.line = 149;
    var it_520094178 = x_520094108.childNodes[idx_520094156[chckIndx(1, 0, (idx_520094156).length - 1)]];
    Label16: {
      F.line = 150;
      var j_520094183 = 0;
      F.line = 126;
      F.filename = "iterators_1.nim";
      var colontmp__520094919 = 0;
      F.line = 150;
      F.filename = "dochack.nim";
      colontmp__520094919 = it_520094178.childNodes.length;
      F.line = 128;
      F.filename = "iterators_1.nim";
      var i_520094920 = 0;
      Label17: {
        F.line = 129;
          Label18: while (true) {
          if (!(i_520094920 < colontmp__520094919)) break Label18;
            F.line = 150;
            F.filename = "dochack.nim";
            j_520094183 = i_520094920;
            F.line = 150;
            toToc_520094107(it_520094178.childNodes[j_520094183], e_520094177);
            F.line = 131;
            F.filename = "iterators_1.nim";
            i_520094920 = addInt(i_520094920, 1);
          }
      };
    };
    F.line = 152;
    F.filename = "dochack.nim";
    father_520094109.kids.push(e_520094177);;
    }
    else {
      Label19: {
        F.line = 154;
        var i_520094192 = 0;
        F.line = 126;
        F.filename = "iterators_1.nim";
        var colontmp__520094923 = 0;
        F.line = 154;
        F.filename = "dochack.nim";
        colontmp__520094923 = x_520094108.childNodes.length;
        F.line = 128;
        F.filename = "iterators_1.nim";
        var i_520094924 = 0;
        Label20: {
          F.line = 129;
            Label21: while (true) {
            if (!(i_520094924 < colontmp__520094923)) break Label21;
              F.line = 154;
              F.filename = "dochack.nim";
              i_520094192 = i_520094924;
              F.line = 154;
              toToc_520094107(x_520094108.childNodes[i_520094192], father_520094109);
              F.line = 131;
              F.filename = "iterators_1.nim";
              i_520094924 = addInt(i_520094924, 1);
            }
        };
      };
    }
    
    }
    else {
      F.line = 157;
      F.filename = "dochack.nim";
    father_520094109.kids.push({heading: x_520094108, kids: [], sortId: (father_520094109.kids).length, doSort: false});;
    }
    }}
  framePtr = F.prev;

  
}

function extractItems_520093895(x_520093896, heading_520093897, items_520093898, items_520093898_Idx) {
  var F = {procname: "dochack.extractItems", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    if ((x_520093896 == null)) {
    F.line = 76;
    F.filename = "dochack.nim";
    break BeforeRet;
    }
    
    if ((!((x_520093896.heading == null)) && (x_520093896.heading.textContent == heading_520093897))) {
    Label1: {
      F.line = 78;
      var i_520093915 = 0;
      F.line = 126;
      F.filename = "iterators_1.nim";
      var colontmp__520094927 = 0;
      F.line = 78;
      F.filename = "dochack.nim";
      colontmp__520094927 = (x_520093896.kids).length;
      F.line = 128;
      F.filename = "iterators_1.nim";
      var i_520094928 = 0;
      Label2: {
        F.line = 129;
          Label3: while (true) {
          if (!(i_520094928 < colontmp__520094927)) break Label3;
            F.line = 78;
            F.filename = "dochack.nim";
            i_520093915 = i_520094928;
            F.line = 78;
            items_520093898[items_520093898_Idx].push(x_520093896.kids[chckIndx(i_520093915, 0, (x_520093896.kids).length - 1)].heading);;
            F.line = 131;
            F.filename = "iterators_1.nim";
            i_520094928 = addInt(i_520094928, 1);
          }
      };
    };
    }
    else {
      Label4: {
        F.line = 81;
        F.filename = "dochack.nim";
        var k_520093941 = null;
        F.line = 249;
        F.filename = "iterators.nim";
        var i_520094932 = 0;
        F.line = 250;
        var L_520094933 = (x_520093896.kids).length;
        Label5: {
          F.line = 251;
            Label6: while (true) {
            if (!(i_520094932 < L_520094933)) break Label6;
              F.line = 81;
              F.filename = "dochack.nim";
              k_520093941 = x_520093896.kids[chckIndx(i_520094932, 0, (x_520093896.kids).length - 1)];
              F.line = 81;
              extractItems_520093895(k_520093941, heading_520093897, items_520093898, items_520093898_Idx);
              F.line = 13;
              F.filename = "iterators.nim";
              i_520094932 += 1;
              if (!(((x_520093896.kids).length == L_520094933))) {
              F.line = 254;
              failedAssertImpl_268435541(makeNimstrLit("/home/runner/work/Arraymancer/Arraymancer/nim/lib/system/iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
              }
              
            }
        };
      };
    }
    
  };
  framePtr = F.prev;

  
}

function tree_520093826(tag_520093827, kids_520093828) {
  var result_520093829 = null;

  var F = {procname: "dochack.tree", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
  framePtr = F;
    F.line = 28;
    F.filename = "dochack.nim";
    result_520093829 = document.createElement(tag_520093827);
    Label1: {
      F.line = 29;
      var k_520093843 = null;
      F.line = 18;
      F.filename = "iterators.nim";
      var i_520094945 = 0;
      Label2: {
        F.line = 19;
          Label3: while (true) {
          if (!(i_520094945 < (kids_520093828).length)) break Label3;
            F.line = 29;
            F.filename = "dochack.nim";
            k_520093843 = kids_520093828[chckIndx(i_520094945, 0, (kids_520093828).length - 1)];
            F.line = 29;
            result_520093829.appendChild(k_520093843);
            F.line = 13;
            F.filename = "iterators.nim";
            i_520094945 += 1;
          }
      };
    };
  framePtr = F.prev;

  return result_520093829;

}

function text_520093851(s_520093852) {
  var result_520093853 = null;

  var F = {procname: "dochack.text", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
  framePtr = F;
    F.line = 42;
    F.filename = "dochack.nim";
    result_520093853 = document.createTextNode(s_520093852);
  framePtr = F.prev;

  return result_520093853;

}

function uncovered_520094296(x_520094297) {
    var Temporary1;

  var result_520094298 = null;

  var F = {procname: "dochack.uncovered", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    if ((((x_520094297.kids).length == 0) && !((x_520094297.heading == null)))) {
    F.line = 171;
    F.filename = "dochack.nim";
    if (!(x_520094297.heading.hasOwnProperty('__karaxMarker__'))) {
    Temporary1 = x_520094297;
    }
    else {
    Temporary1 = null;
    }
    
    result_520094298 = Temporary1;
    break BeforeRet;
    }
    
    F.line = 172;
    result_520094298 = {heading: x_520094297.heading, kids: [], sortId: x_520094297.sortId, doSort: x_520094297.doSort};
    Label2: {
      F.line = 174;
      var k_520094313 = null;
      F.line = 249;
      F.filename = "iterators.nim";
      var i_520094952 = 0;
      F.line = 250;
      var L_520094953 = (x_520094297.kids).length;
      Label3: {
        F.line = 251;
          Label4: while (true) {
          if (!(i_520094952 < L_520094953)) break Label4;
            F.line = 174;
            F.filename = "dochack.nim";
            k_520094313 = x_520094297.kids[chckIndx(i_520094952, 0, (x_520094297.kids).length - 1)];
            F.line = 175;
            var y_520094314 = uncovered_520094296(k_520094313);
            if (!((y_520094314 == null))) {
            F.line = 176;
            result_520094298.kids.push(y_520094314);;
            }
            
            F.line = 13;
            F.filename = "iterators.nim";
            i_520094952 += 1;
            if (!(((x_520094297.kids).length == L_520094953))) {
            F.line = 254;
            failedAssertImpl_268435541(makeNimstrLit("/home/runner/work/Arraymancer/Arraymancer/nim/lib/system/iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    if (((result_520094298.kids).length == 0)) {
    F.line = 177;
    F.filename = "dochack.nim";
    result_520094298 = null;
    }
    
  };
  framePtr = F.prev;

  return result_520094298;

}

function mergeTocs_520094326(orig_520094327, news_520094328) {
  var result_520094329 = null;

  var F = {procname: "dochack.mergeTocs", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
  framePtr = F;
    F.line = 180;
    F.filename = "dochack.nim";
    result_520094329 = uncovered_520094296(orig_520094327);
    if ((result_520094329 == null)) {
    F.line = 182;
    result_520094329 = news_520094328;
    }
    else {
      Label1: {
        F.line = 184;
        var i_520094341 = 0;
        F.line = 126;
        F.filename = "iterators_1.nim";
        var colontmp__520094948 = 0;
        F.line = 184;
        F.filename = "dochack.nim";
        colontmp__520094948 = (news_520094328.kids).length;
        F.line = 128;
        F.filename = "iterators_1.nim";
        var i_520094949 = 0;
        Label2: {
          F.line = 129;
            Label3: while (true) {
            if (!(i_520094949 < colontmp__520094948)) break Label3;
              F.line = 184;
              F.filename = "dochack.nim";
              i_520094341 = i_520094949;
              F.line = 184;
              result_520094329.kids.push(news_520094328.kids[chckIndx(i_520094341, 0, (news_520094328.kids).length - 1)]);;
              F.line = 131;
              F.filename = "iterators_1.nim";
              i_520094949 = addInt(i_520094949, 1);
            }
        };
      };
    }
    
  framePtr = F.prev;

  return result_520094329;

}

function buildToc_520094346(orig_520094347, types_520094348, procs_520094349) {
  var result_520094350 = null;

  var F = {procname: "dochack.buildToc", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
  framePtr = F;
    F.line = 188;
    F.filename = "dochack.nim";
    var newStuff_520094355 = {heading: null, kids: [], doSort: true, sortId: 0};
    Label1: {
      F.line = 189;
      var t_520094359 = null;
      F.line = 249;
      F.filename = "iterators.nim";
      var i_520094940 = 0;
      F.line = 250;
      var L_520094941 = (types_520094348).length;
      Label2: {
        F.line = 251;
          Label3: while (true) {
          if (!(i_520094940 < L_520094941)) break Label3;
            F.line = 189;
            F.filename = "dochack.nim";
            t_520094359 = types_520094348[chckIndx(i_520094940, 0, (types_520094348).length - 1)];
            F.line = 190;
            var c_520094364 = {heading: t_520094359.cloneNode(true), kids: [], doSort: true, sortId: 0};
            F.line = 189;
            t_520094359.__karaxMarker__ = true;
            Label4: {
              F.line = 192;
              var p_520094368 = null;
              F.line = 249;
              F.filename = "iterators.nim";
              var i_520094937 = 0;
              F.line = 250;
              var L_520094938 = (procs_520094349).length;
              Label5: {
                F.line = 251;
                  Label6: while (true) {
                  if (!(i_520094937 < L_520094938)) break Label6;
                    F.line = 192;
                    F.filename = "dochack.nim";
                    p_520094368 = procs_520094349[chckIndx(i_520094937, 0, (procs_520094349).length - 1)];
                    if (!(p_520094368.hasOwnProperty('__karaxMarker__'))) {
                    F.line = 194;
                    var xx_520094369 = p_520094368.parentNode.getElementsByClassName("attachedType");
                    if ((((xx_520094369).length == 1) && (xx_520094369[chckIndx(0, 0, (xx_520094369).length - 1)].textContent == t_520094359.textContent))) {
                    F.line = 196;
                    var q_520094374 = tree_520093826("A", [text_520093851(p_520094368.title)]);
                    F.line = 197;
                    q_520094374.setAttribute("href", p_520094368.getAttribute("href"));
                    F.line = 198;
                    c_520094364.kids.push({heading: q_520094374, kids: [], sortId: 0, doSort: false});;
                    F.line = 199;
                    p_520094368.__karaxMarker__ = true;
                    }
                    
                    }
                    
                    F.line = 13;
                    F.filename = "iterators.nim";
                    i_520094937 += 1;
                    if (!(((procs_520094349).length == L_520094938))) {
                    F.line = 254;
                    failedAssertImpl_268435541(makeNimstrLit("/home/runner/work/Arraymancer/Arraymancer/nim/lib/system/iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
                    }
                    
                  }
              };
            };
            F.line = 189;
            F.filename = "dochack.nim";
            newStuff_520094355.kids.push(c_520094364);;
            F.line = 13;
            F.filename = "iterators.nim";
            i_520094940 += 1;
            if (!(((types_520094348).length == L_520094941))) {
            F.line = 254;
            failedAssertImpl_268435541(makeNimstrLit("/home/runner/work/Arraymancer/Arraymancer/nim/lib/system/iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    F.line = 201;
    F.filename = "dochack.nim";
    result_520094350 = mergeTocs_520094326(orig_520094347, newStuff_520094355);
  framePtr = F.prev;

  return result_520094350;

}

function add_520093844(parent_520093845, kid_520093846) {
  var F = {procname: "dochack.add", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
  framePtr = F;
    if (((parent_520093845.nodeName == "TR") && ((kid_520093846.nodeName == "TD") || (kid_520093846.nodeName == "TH")))) {
    F.line = 34;
    F.filename = "dochack.nim";
    var k_520093847 = document.createElement("TD");
    F.line = 35;
    k_520093847.appendChild(kid_520093846);
    F.line = 36;
    parent_520093845.appendChild(k_520093847);
    }
    else {
      F.line = 38;
    parent_520093845.appendChild(kid_520093846);
    }
    
  framePtr = F.prev;

  
}

function setClass_520093848(e_520093849, value_520093850) {
  var F = {procname: "dochack.setClass", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
  framePtr = F;
    F.line = 41;
    F.filename = "dochack.nim";
    e_520093849.setAttribute("class", value_520093850);
  framePtr = F.prev;

  
}

function toHtml_520093974(x_520093975, isRoot_520093976) {
    
function HEX3Aanonymous_520093994(a_520093995, b_520093996) {
      var result_520093997 = 0;

      var F = {procname: "toHtml.:anonymous", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
      framePtr = F;
      BeforeRet: {
        if ((!((a_520093995.heading == null)) && !((b_520093996.heading == null)))) {
        F.line = 100;
        F.filename = "dochack.nim";
        var x_520094006 = a_520093995.heading.textContent;
        F.line = 101;
        var y_520094007 = b_520093996.heading.textContent;
        if ((x_520094006 < y_520094007)) {
        F.line = 102;
        result_520093997 = (-1);
        break BeforeRet;
        }
        
        if ((y_520094007 < x_520094006)) {
        F.line = 103;
        result_520093997 = 1;
        break BeforeRet;
        }
        
        F.line = 104;
        result_520093997 = 0;
        break BeforeRet;
        }
        else {
          F.line = 107;
          result_520093997 = subInt(a_520093995.sortId, b_520093996.sortId);
          break BeforeRet;
        }
        
      };
      framePtr = F.prev;

      return result_520093997;

    }

  var result_520093977 = null;

  var F = {procname: "dochack.toHtml", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    if ((x_520093975 == null)) {
    F.line = 85;
    F.filename = "dochack.nim";
    result_520093977 = null;
    break BeforeRet;
    }
    
    if (((x_520093975.kids).length == 0)) {
    if ((x_520093975.heading == null)) {
    F.line = 87;
    result_520093977 = null;
    break BeforeRet;
    }
    
    F.line = 88;
    result_520093977 = x_520093975.heading.cloneNode(true);
    break BeforeRet;
    }
    
    F.line = 89;
    result_520093977 = tree_520093826("DIV", []);
    if ((!((x_520093975.heading == null)) && !(x_520093975.heading.hasOwnProperty('__karaxMarker__')))) {
    F.line = 91;
    add_520093844(result_520093977, x_520093975.heading.cloneNode(true));
    }
    
    F.line = 92;
    var ul_520093993 = tree_520093826("UL", []);
    if (isRoot_520093976) {
    F.line = 94;
    setClass_520093848(ul_520093993, "simple simple-toc");
    }
    else {
      F.line = 96;
    setClass_520093848(ul_520093993, "simple");
    }
    
    if (x_520093975.doSort) {
    F.line = 98;
    x_520093975.kids.sort(HEX3Aanonymous_520093994);
    }
    
    Label1: {
      F.line = 109;
      var k_520094019 = null;
      F.line = 249;
      F.filename = "iterators.nim";
      var i_520094956 = 0;
      F.line = 250;
      var L_520094957 = (x_520093975.kids).length;
      Label2: {
        F.line = 251;
          Label3: while (true) {
          if (!(i_520094956 < L_520094957)) break Label3;
            F.line = 109;
            F.filename = "dochack.nim";
            k_520094019 = x_520093975.kids[chckIndx(i_520094956, 0, (x_520093975.kids).length - 1)];
            F.line = 110;
            var y_520094020 = toHtml_520093974(k_520094019, false);
            if (!((y_520094020 == null))) {
            F.line = 112;
            add_520093844(ul_520093993, tree_520093826("LI", [y_520094020]));
            }
            
            F.line = 13;
            F.filename = "iterators.nim";
            i_520094956 += 1;
            if (!(((x_520093975.kids).length == L_520094957))) {
            F.line = 254;
            failedAssertImpl_268435541(makeNimstrLit("/home/runner/work/Arraymancer/Arraymancer/nim/lib/system/iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    if (!((ul_520093993.childNodes.length == 0))) {
    F.line = 113;
    F.filename = "dochack.nim";
    add_520093844(result_520093977, ul_520093993);
    }
    
    if ((result_520093977.childNodes.length == 0)) {
    F.line = 114;
    result_520093977 = null;
    }
    
  };
  framePtr = F.prev;

  return result_520093977;

}

function replaceById_520093854(id_520093855, newTree_520093856) {
  var F = {procname: "dochack.replaceById", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
  framePtr = F;
    F.line = 45;
    F.filename = "dochack.nim";
    var x_520093857 = document.getElementById(id_520093855);
    F.line = 46;
    x_520093857.parentNode.replaceChild(newTree_520093856, x_520093857);
    F.line = 47;
    newTree_520093856.id = id_520093855;
  framePtr = F.prev;

  
}

function togglevis_520094404(d_520094405) {
  var F = {procname: "dochack.togglevis", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
  framePtr = F;
    if ((d_520094405.style.display == "none")) {
    F.line = 207;
    F.filename = "dochack.nim";
    d_520094405.style.display = "inline";
    }
    else {
      F.line = 209;
      d_520094405.style.display = "none";
    }
    
  framePtr = F.prev;

  
}

function groupBy(value_520094407) {
  var F = {procname: "dochack.groupBy", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
  framePtr = F;
    F.line = 212;
    F.filename = "dochack.nim";
    var toc_520094408 = document.getElementById("toc-list");
    if ((alternative_520094403[0] == null)) {
    F.line = 214;
    var tt_520094416 = {heading: null, kids: [], sortId: 0, doSort: false};
    F.line = 215;
    toToc_520094107(toc_520094408, tt_520094416);
    F.line = 216;
    tt_520094416 = tt_520094416.kids[chckIndx(0, 0, (tt_520094416.kids).length - 1)];
    F.line = 218;
    var types_520094421 = [[]];
    F.line = 219;
    var procs_520094426 = [[]];
    F.line = 221;
    extractItems_520093895(tt_520094416, "Types", types_520094421, 0);
    F.line = 222;
    extractItems_520093895(tt_520094416, "Procs", procs_520094426, 0);
    F.line = 223;
    extractItems_520093895(tt_520094416, "Converters", procs_520094426, 0);
    F.line = 224;
    extractItems_520093895(tt_520094416, "Methods", procs_520094426, 0);
    F.line = 225;
    extractItems_520093895(tt_520094416, "Templates", procs_520094426, 0);
    F.line = 226;
    extractItems_520093895(tt_520094416, "Macros", procs_520094426, 0);
    F.line = 227;
    extractItems_520093895(tt_520094416, "Iterators", procs_520094426, 0);
    F.line = 229;
    var ntoc_520094427 = buildToc_520094346(tt_520094416, types_520094421[0], procs_520094426[0]);
    F.line = 230;
    var x_520094428 = toHtml_520093974(ntoc_520094427, true);
    F.line = 231;
    alternative_520094403[0] = tree_520093826("DIV", [x_520094428]);
    }
    
    if ((value_520094407 == "type")) {
    F.line = 233;
    replaceById_520093854("tocRoot", alternative_520094403[0]);
    }
    else {
      F.line = 235;
    replaceById_520093854("tocRoot", tree_520093826("DIV", []));
    }
    
    F.line = 236;
    togglevis_520094404(document.getElementById("toc-list"));
  framePtr = F.prev;

  
}

function HEX5BHEX5D_687867163(s_687867166, x_687867167) {
  var result_687867168 = [];

  var F = {procname: "[].[]", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/system/indices.nim", line: 0};
  framePtr = F;
    F.line = 83;
    F.filename = "indices.nim";
    var a_687867170 = x_687867167.a;
    F.line = 84;
    var L_687867172 = addInt(subInt(subInt((s_687867166).length, x_687867167.b), a_687867170), 1);
    F.line = 85;
    result_687867168 = nimCopy(null, mnewString(chckRange(L_687867172, 0, 2147483647)), NTI33554449);
    Label1: {
      F.line = 86;
      var i_687867177 = 0;
      F.line = 128;
      F.filename = "iterators_1.nim";
      var i_520094966 = 0;
      Label2: {
        F.line = 129;
          Label3: while (true) {
          if (!(i_520094966 < L_687867172)) break Label3;
            F.line = 86;
            F.filename = "indices.nim";
            i_687867177 = i_520094966;
            F.line = 86;
            result_687867168[chckIndx(i_687867177, 0, (result_687867168).length - 1)] = s_687867166[chckIndx(addInt(i_687867177, a_687867170), 0, (s_687867166).length - 1)];
            F.line = 131;
            F.filename = "iterators_1.nim";
            i_520094966 = addInt(i_520094966, 1);
          }
      };
    };
  framePtr = F.prev;

  return result_687867168;

}

function HEX2EHEX2E_872415337(a_872415340, b_872415341) {
  var result_872415344 = ({a: 0, b: 0});

  var F = {procname: ".....", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 416;
    F.filename = "system.nim";
    result_872415344 = nimCopy(result_872415344, {a: a_872415340, b: b_872415341}, NTI872415317);
  framePtr = F.prev;

  return result_872415344;

}
async function loadIndex_520094624() {
  var result_520094626 = null;

  var F = {procname: "dochack.loadIndex", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 286;
    F.filename = "dochack.nim";
    var indexURL_520094632 = document.getElementById("indexLink").getAttribute("href");
    F.line = 288;
    var rootURL_520094658 = HEX5BHEX5D_687867163(cstrToNimstr(indexURL_520094632), HEX2EHEX2E_872415337(0, 14));
    F.line = 289;
    var resp_520094670 = (await (await fetch(indexURL_520094632)).text());
    F.line = 291;
    var indexElem_520094671 = document.createElement("div");
    F.line = 292;
    indexElem_520094671.innerHTML = resp_520094670;
    Label1: {
      F.line = 294;
      var href_520094693 = null;
      F.line = 247;
      F.filename = "iterators.nim";
      var colontmp__520094960 = [];
      F.line = 294;
      F.filename = "dochack.nim";
      colontmp__520094960 = indexElem_520094671.getElementsByClassName("reference");
      F.line = 249;
      F.filename = "iterators.nim";
      var i_520094962 = 0;
      F.line = 250;
      var L_520094963 = (colontmp__520094960).length;
      Label2: {
        F.line = 251;
          Label3: while (true) {
          if (!(i_520094962 < L_520094963)) break Label3;
            F.line = 294;
            F.filename = "dochack.nim";
            href_520094693 = colontmp__520094960[chckIndx(i_520094962, 0, (colontmp__520094960).length - 1)];
            F.line = 294;
            href_520094693.setAttribute("href", toJSStr((rootURL_520094658 || []).concat(cstrToNimstr(href_520094693.getAttribute("href")) || [])));
            F.line = 297;
            db_520094445[0].push(href_520094693);;
            F.line = 298;
            contents_520094446[0].push(href_520094693.getAttribute("data-doc-search-tag"));;
            F.line = 13;
            F.filename = "iterators.nim";
            i_520094962 += 1;
            if (!(((colontmp__520094960).length == L_520094963))) {
            F.line = 254;
            failedAssertImpl_268435541(makeNimstrLit("/home/runner/work/Arraymancer/Arraymancer/nim/lib/system/iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    F.line = 148;
    F.filename = "asyncjs.nim";
    result_520094626 = undefined;
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_520094626;

}

function then_520094802(future_520094805, onSuccess_520094806, onReject_520094807) {
  var result_520094808 = null;

  var F = {procname: "then.then", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/js/asyncjs.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 243;
    F.filename = "asyncjs.nim";
    var ret_520094818 = null;
    F.line = 244;
    ret_520094818 = future_520094805.then(onSuccess_520094806, onReject_520094807)
    F.line = 245;
    result_520094808 = ret_520094818;
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_520094808;

}

function nsuToLowerAsciiChar(c_687865941) {
  var result_687865942 = 0;

  var F = {procname: "strutils.toLowerAscii", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
    if ((ConstSet2[c_687865941] != undefined)) {
    F.line = 218;
    F.filename = "strutils.nim";
    result_687865942 = (c_687865941 ^ 32);
    }
    else {
      F.line = 220;
      result_687865942 = c_687865941;
    }
    
  framePtr = F.prev;

  return result_687865942;

}

function fuzzyMatch_671088656(pattern_671088657, str_671088658) {
              var Temporary4;
              var Temporary5;
                var Temporary6;
      var Temporary7;
        var Temporary8;

  var result_671088661 = {Field0: 0, Field1: false};

  var F = {procname: "fuzzysearch.fuzzyMatch", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/fuzzysearch.nim", line: 0};
  framePtr = F;
    F.line = 36;
    F.filename = "fuzzysearch.nim";
    var scoreState_671088662 = (-100);
    F.line = 37;
    var headerMatched_671088663 = false;
    F.line = 38;
    var unmatchedLeadingCharCount_671088664 = 0;
    F.line = 39;
    var consecutiveMatchCount_671088665 = 0;
    F.line = 40;
    var strIndex_671088666 = 0;
    F.line = 41;
    var patIndex_671088667 = 0;
    F.line = 42;
    var score_671088668 = 0;
    Label1: {
      F.line = 48;
        Label2: while (true) {
        if (!((strIndex_671088666 < ((str_671088658) == null ? 0 : (str_671088658).length)) && (patIndex_671088667 < ((pattern_671088657) == null ? 0 : (pattern_671088657).length)))) break Label2;
          Label3: {
            F.line = 50;
            var patternChar_671088671 = nsuToLowerAsciiChar(pattern_671088657.charCodeAt(chckIndx(patIndex_671088667, 0, (pattern_671088657).length - 1)));
            F.line = 51;
            var strChar_671088672 = nsuToLowerAsciiChar(str_671088658.charCodeAt(chckIndx(strIndex_671088666, 0, (str_671088658).length - 1)));
            if ((ConstSet3[patternChar_671088671] != undefined)) {
            F.line = 55;
            patIndex_671088667 = addInt(patIndex_671088667, 1);
            F.line = 56;
            break Label3;
            }
            
            if ((ConstSet4[strChar_671088672] != undefined)) {
            F.line = 58;
            strIndex_671088666 = addInt(strIndex_671088666, 1);
            F.line = 59;
            break Label3;
            }
            
            if ((!(headerMatched_671088663) && (strChar_671088672 == 58))) {
            F.line = 64;
            headerMatched_671088663 = true;
            F.line = 65;
            scoreState_671088662 = (-100);
            F.line = 66;
            score_671088668 = ((Math.floor((0.5 * score_671088668))) | 0);
            F.line = 67;
            patIndex_671088667 = 0;
            F.line = 68;
            strIndex_671088666 = addInt(strIndex_671088666, 1);
            F.line = 69;
            break Label3;
            }
            
            if ((strChar_671088672 == patternChar_671088671)) {
            F.line = 72;
            switch (scoreState_671088662) {
            case (-100):
            case 20:
              F.line = 74;
              scoreState_671088662 = 10;
              break;
            case 0:
              F.line = 77;
              scoreState_671088662 = 5;
              F.line = 77;
              score_671088668 = addInt(score_671088668, scoreState_671088662);
              break;
            case 10:
            case 5:
              F.line = 80;
              consecutiveMatchCount_671088665 = addInt(consecutiveMatchCount_671088665, 1);
              F.line = 81;
              scoreState_671088662 = 5;
              F.line = 82;
              score_671088668 = addInt(score_671088668, mulInt(5, consecutiveMatchCount_671088665));
              if ((scoreState_671088662 == 10)) {
              F.line = 85;
              score_671088668 = addInt(score_671088668, 10);
              }
              
              F.line = 87;
              var onBoundary_671088724 = (patIndex_671088667 == ((pattern_671088657) == null ? -1 : (pattern_671088657).length - 1));
              if ((!(onBoundary_671088724) && (strIndex_671088666 < ((str_671088658) == null ? -1 : (str_671088658).length - 1)))) {
              F.line = 90;
              var nextPatternChar_671088725 = nsuToLowerAsciiChar(pattern_671088657.charCodeAt(chckIndx(addInt(patIndex_671088667, 1), 0, (pattern_671088657).length - 1)));
              F.line = 91;
              var nextStrChar_671088726 = nsuToLowerAsciiChar(str_671088658.charCodeAt(chckIndx(addInt(strIndex_671088666, 1), 0, (str_671088658).length - 1)));
              F.line = 94;
              if (!!((ConstSet5[nextStrChar_671088726] != undefined))) Temporary4 = false; else {                Temporary4 = !((nextStrChar_671088726 == nextPatternChar_671088725));              }              onBoundary_671088724 = Temporary4;
              }
              
              if (onBoundary_671088724) {
              F.line = 99;
              scoreState_671088662 = 20;
              F.line = 99;
              score_671088668 = addInt(score_671088668, scoreState_671088662);
              }
              
              break;
            case (-1):
            case (-3):
              F.line = 102;
              if (!((ConstSet6[str_671088658.charCodeAt(chckIndx(subInt(strIndex_671088666, 1), 0, (str_671088658).length - 1))] != undefined))) Temporary5 = true; else {                if (!(ConstSet7[str_671088658.charCodeAt(chckIndx(subInt(strIndex_671088666, 1), 0, (str_671088658).length - 1))] != undefined)) Temporary6 = false; else {                  Temporary6 = (ConstSet8[str_671088658.charCodeAt(chckIndx(strIndex_671088666, 0, (str_671088658).length - 1))] != undefined);                }                Temporary5 = Temporary6;              }              var isLeadingChar_671088750 = Temporary5;
              if (isLeadingChar_671088750) {
              F.line = 109;
              scoreState_671088662 = 10;
              }
              else {
                F.line = 113;
                scoreState_671088662 = 0;
                F.line = 113;
                score_671088668 = addInt(score_671088668, scoreState_671088662);
              }
              
              break;
            }
            F.line = 114;
            patIndex_671088667 = addInt(patIndex_671088667, 1);
            }
            else {
              F.line = 117;
              switch (scoreState_671088662) {
              case (-100):
                F.line = 119;
                scoreState_671088662 = (-3);
                F.line = 119;
                score_671088668 = addInt(score_671088668, scoreState_671088662);
                break;
              case 5:
                F.line = 122;
                scoreState_671088662 = (-1);
                F.line = 122;
                score_671088668 = addInt(score_671088668, scoreState_671088662);
                F.line = 123;
                consecutiveMatchCount_671088665 = 0;
                break;
              case (-3):
                if ((unmatchedLeadingCharCount_671088664 < 3)) {
                F.line = 127;
                scoreState_671088662 = (-3);
                F.line = 127;
                score_671088668 = addInt(score_671088668, scoreState_671088662);
                }
                
                F.line = 128;
                unmatchedLeadingCharCount_671088664 = addInt(unmatchedLeadingCharCount_671088664, 1);
                break;
              default: 
                F.line = 131;
                scoreState_671088662 = (-1);
                F.line = 131;
                score_671088668 = addInt(score_671088668, scoreState_671088662);
                break;
              }
            }
            
            F.line = 133;
            strIndex_671088666 = addInt(strIndex_671088666, 1);
          };
        }
    };
      if (!(patIndex_671088667 == ((pattern_671088657) == null ? 0 : (pattern_671088657).length))) Temporary7 = false; else {        if ((strIndex_671088666 == ((str_671088658) == null ? 0 : (str_671088658).length))) Temporary8 = true; else {          Temporary8 = !((ConstSet9[str_671088658.charCodeAt(chckIndx(strIndex_671088666, 0, (str_671088658).length - 1))] != undefined));        }        Temporary7 = Temporary8;      }    if (Temporary7) {
    F.line = 136;
    score_671088668 = addInt(score_671088668, 10);
    }
    
    F.line = 139;
    var colontmp__520094979 = nimMax(0, score_671088668);
    F.line = 140;
    var colontmp__520094980 = (0 < score_671088668);
    F.line = 138;
    result_671088661 = nimCopy(result_671088661, {Field0: colontmp__520094979, Field1: colontmp__520094980}, NTI671088654);
  framePtr = F.prev;

  return result_671088661;

}

function escapeCString_520094447(x_520094448, x_520094448_Idx) {
  var F = {procname: "dochack.escapeCString", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
  framePtr = F;
    F.line = 246;
    F.filename = "dochack.nim";
    var s_520094449 = [];
    Label1: {
      F.line = 247;
      var c_520094450 = 0;
      F.line = 83;
      F.filename = "iterators.nim";
      var iHEX60gensym13_520094983 = 0;
      F.line = 84;
      var nHEX60gensym13_520094984 = ((x_520094448[x_520094448_Idx]) == null ? 0 : (x_520094448[x_520094448_Idx]).length);
      Label2: {
        F.line = 88;
          Label3: while (true) {
          if (!(iHEX60gensym13_520094983 < nHEX60gensym13_520094984)) break Label3;
            F.line = 247;
            F.filename = "dochack.nim";
            c_520094450 = x_520094448[x_520094448_Idx].charCodeAt(chckIndx(iHEX60gensym13_520094983, 0, (x_520094448[x_520094448_Idx]).length - 1));
            F.line = 247;
            switch (c_520094450) {
            case 60:
              F.line = 249;
              s_520094449.push.apply(s_520094449, [38,108,116,59]);;
              break;
            case 62:
              F.line = 250;
              s_520094449.push.apply(s_520094449, [38,103,116,59]);;
              break;
            default: 
              F.line = 251;
              addChar(s_520094449, c_520094450);;
              break;
            }
            F.line = 13;
            F.filename = "iterators.nim";
            iHEX60gensym13_520094983 += 1;
          }
      };
    };
    F.line = 252;
    F.filename = "dochack.nim";
    x_520094448[x_520094448_Idx] = toJSStr(s_520094449);
  framePtr = F.prev;

  
}

function dosearch_520094451(value_520094452) {
    
function HEX3Aanonymous_520094479(a_520094484, b_520094485) {
      var result_520094492 = 0;

      var F = {procname: "dosearch.:anonymous", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
      framePtr = F;
        F.line = 272;
        F.filename = "dochack.nim";
        result_520094492 = subInt(b_520094485["Field1"], a_520094484["Field1"]);
      framePtr = F.prev;

      return result_520094492;

    }

  var result_520094453 = null;

  var F = {procname: "dochack.dosearch", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    if (((db_520094445[0]).length == 0)) {
    F.line = 256;
    F.filename = "dochack.nim";
    break BeforeRet;
    }
    
    F.line = 257;
    var ul_520094457 = tree_520093826("UL", []);
    F.line = 258;
    result_520094453 = tree_520093826("DIV", []);
    F.line = 259;
    setClass_520093848(result_520094453, "search_results");
    F.line = 260;
    var matches_520094462 = [];
    Label1: {
      F.line = 261;
      var i_520094470 = 0;
      F.line = 126;
      F.filename = "iterators_1.nim";
      var colontmp__520094970 = 0;
      F.line = 261;
      F.filename = "dochack.nim";
      colontmp__520094970 = (db_520094445[0]).length;
      F.line = 128;
      F.filename = "iterators_1.nim";
      var i_520094971 = 0;
      Label2: {
        F.line = 129;
          Label3: while (true) {
          if (!(i_520094971 < colontmp__520094970)) break Label3;
            F.line = 261;
            F.filename = "dochack.nim";
            i_520094470 = i_520094971;
            Label4: {
              F.line = 262;
              var c_520094471 = contents_520094446[0][chckIndx(i_520094470, 0, (contents_520094446[0]).length - 1)];
              if (((c_520094471 == "Examples") || (c_520094471 == "PEG construction"))) {
              F.line = 267;
              break Label4;
              }
              
              F.line = 268;
              var tmpTuple_520094472 = fuzzyMatch_671088656(value_520094452, c_520094471);
              F.line = 268;
              var score_520094473 = tmpTuple_520094472["Field0"];
              F.line = 268;
              var matched_520094474 = tmpTuple_520094472["Field1"];
              if (matched_520094474) {
              F.line = 270;
              matches_520094462.push({Field0: db_520094445[0][chckIndx(i_520094470, 0, (db_520094445[0]).length - 1)], Field1: score_520094473});;
              }
              
            };
            F.line = 131;
            F.filename = "iterators_1.nim";
            i_520094971 = addInt(i_520094971, 1);
          }
      };
    };
    F.line = 272;
    F.filename = "dochack.nim";
    matches_520094462.sort(HEX3Aanonymous_520094479);
    Label5: {
      F.line = 273;
      var i_520094509 = 0;
      F.line = 126;
      F.filename = "iterators_1.nim";
      var colontmp__520094974 = 0;
      F.line = 273;
      F.filename = "dochack.nim";
      colontmp__520094974 = nimMin((matches_520094462).length, 29);
      F.line = 128;
      F.filename = "iterators_1.nim";
      var i_520094975 = 0;
      Label6: {
        F.line = 129;
          Label7: while (true) {
          if (!(i_520094975 < colontmp__520094974)) break Label7;
            F.line = 273;
            F.filename = "dochack.nim";
            i_520094509 = i_520094975;
            F.line = 274;
            matches_520094462[chckIndx(i_520094509, 0, (matches_520094462).length - 1)]["Field0"].innerHTML = matches_520094462[chckIndx(i_520094509, 0, (matches_520094462).length - 1)]["Field0"].getAttribute("data-doc-search-tag");
            F.line = 273;
            escapeCString_520094447(matches_520094462[chckIndx(i_520094509, 0, (matches_520094462).length - 1)]["Field0"], "innerHTML");
            F.line = 273;
            add_520093844(ul_520094457, tree_520093826("LI", [matches_520094462[chckIndx(i_520094509, 0, (matches_520094462).length - 1)]["Field0"]]));
            F.line = 131;
            F.filename = "iterators_1.nim";
            i_520094975 = addInt(i_520094975, 1);
          }
      };
    };
    if ((ul_520094457.childNodes.length == 0)) {
    F.line = 278;
    F.filename = "dochack.nim";
    add_520093844(result_520094453, tree_520093826("B", [text_520093851("no search results")]));
    }
    else {
      F.line = 280;
      add_520093844(result_520094453, tree_520093826("B", [text_520093851("search results")]));
      F.line = 281;
      add_520093844(result_520094453, ul_520094457);
    }
    
  };
  framePtr = F.prev;

  return result_520094453;

}

function search() {
    
function wrapper_520094787() {
      var F = {procname: "search.wrapper", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
      framePtr = F;
        F.line = 308;
        F.filename = "dochack.nim";
        var elem_520094788 = document.getElementById("searchInput");
        F.line = 309;
        var value_520094789 = elem_520094788.value;
        if (!((((value_520094789) == null ? 0 : (value_520094789).length) == 0))) {
        if ((oldtoc_520094782[0] == null)) {
        F.line = 312;
        oldtoc_520094782[0] = document.getElementById("tocRoot");
        }
        
        F.line = 313;
        var results_520094793 = dosearch_520094451(value_520094789);
        F.line = 314;
        replaceById_520093854("tocRoot", results_520094793);
        }
        else {
        if (!((oldtoc_520094782[0] == null))) {
        F.line = 316;
        replaceById_520093854("tocRoot", oldtoc_520094782[0]);
        }
        }
      framePtr = F.prev;

      
    }

  var F = {procname: "dochack.search", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
  framePtr = F;
    if ((loadIndexFut_520094785[0] == null)) {
    F.line = 320;
    F.filename = "dochack.nim";
    loadIndexFut_520094785[0] = loadIndex_520094624();
    F.line = 322;
    var _ = then_520094802(loadIndexFut_520094785[0], wrapper_520094787, null);
    }
    
    if (!((timer_520094783[0] == null))) {
    F.line = 323;
    clearTimeout(timer_520094783[0]);
    }
    
    F.line = 324;
    timer_520094783[0] = setTimeout(wrapper_520094787, 400);
  framePtr = F.prev;

  
}

function copyToClipboard() {
  var F = {procname: "dochack.copyToClipboard", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
  framePtr = F;
    F.line = 327;
    F.filename = "dochack.nim";
    
    function updatePreTags() {

      const allPreTags = document.querySelectorAll("pre")
    
      allPreTags.forEach((e) => {
      
          const div = document.createElement("div")
          div.classList.add("copyToClipBoard")
    
          const preTag = document.createElement("pre")
          preTag.innerHTML = e.innerHTML
    
          const button = document.createElement("button")
          button.value = e.textContent.replace('...', '') 
          button.classList.add("copyToClipBoardBtn")
          button.style.cursor = "pointer"
    
          div.appendChild(preTag)
          div.appendChild(button)
    
          e.outerHTML = div.outerHTML
      
      })
    }


    function copyTextToClipboard(e) {
        const clipBoardContent = e.target.value
        navigator.clipboard.writeText(clipBoardContent).then(function() {
            e.target.style.setProperty("--clipboard-image", "var(--clipboard-image-selected)")
        }, function(err) {
            console.error("Could not copy text: ", err);
        });
    }

    window.addEventListener("click", (e) => {
        if (e.target.classList.contains("copyToClipBoardBtn")) {
            copyTextToClipboard(e)
          }
    })

    window.addEventListener("mouseover", (e) => {
        if (e.target.nodeName === "PRE") {
            e.target.nextElementSibling.style.setProperty("--clipboard-image", "var(--clipboard-image-normal)")
        }
    })
    
    window.addEventListener("DOMContentLoaded", updatePreTags)

    
  framePtr = F.prev;

  
}
var Temporary1;
var F = {procname: "module dochack", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
framePtr = F;
F.line = 11;
F.filename = "dochack.nim";
F.line = 12;
var t_520093735 = window.localStorage.getItem("theme");
if ((t_520093735 == null)) {
Temporary1 = "auto";
}
else {
Temporary1 = t_520093735;
}

setTheme(Temporary1);
F.line = 203;
var alternative_520094403 = [null];
F.line = 239;
var db_520094445 = [[]];
F.line = 240;
var contents_520094446 = [[]];
F.line = 302;
var oldtoc_520094782 = [null];
F.line = 303;
var timer_520094783 = [null];
F.line = 304;
var loadIndexFut_520094785 = [null];
F.line = 381;
copyToClipboard();
F.line = 382;
window.addEventListener("DOMContentLoaded", onDOMLoaded, false);
framePtr = F.prev;
var F = {procname: "module dochack", prev: framePtr, filename: "/home/runner/work/Arraymancer/Arraymancer/nim/tools/dochack/dochack.nim", line: 0};
framePtr = F;
framePtr = F.prev;
